# Generated by Django 4.2.6 on 2024-02-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_verify_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify_email',
            name='hash',
            field=models.CharField(default=21, max_length=100),
            preserve_default=False,
        ),
    ]
