# Generated by Django 5.0.3 on 2024-04-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='quantity',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
