# Generated by Django 4.2.6 on 2024-04-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productdb_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='category',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
