# Generated by Django 5.0.3 on 2024-04-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('profile', models.EmailField(max_length=254, unique=True)),
                ('data', models.CharField(max_length=128)),
                ('additional_params', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.DeleteModel(
            name='ProductDB',
        ),
        migrations.DeleteModel(
            name='Verify_Email',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
